_format_version: "3.0"
plugins:
- config:
    credentials: false
    exposed_headers: null
    headers: null
    max_age: null
    methods:
    - GET
    - HEAD
    - PUT
    - PATCH
    - POST
    - DELETE
    - OPTIONS
    - TRACE
    - CONNECT
    origins: null
    preflight_continue: false
    private_network: false
  enabled: true
  name: cors
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: employee
  name: employee.service
  path: /employees
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - PUT
    - POST
    - DELETE
    - OPTIONS
    name: employees.route
    path_handling: v0
    paths:
    - /employees
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: leaves
  name: leaves.service
  path: /leaves
  plugins:
  - config:
      credentials: false
      exposed_headers: null
      headers: null
      max_age: null
      methods:
      - GET
      - HEAD
      - PUT
      - PATCH
      - POST
      - DELETE
      - OPTIONS
      - TRACE
      - CONNECT
      origins: null
      preflight_continue: false
      private_network: false
    enabled: true
    name: cors
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - PUT
    - POST
    - DELETE
    name: leaves.route
    path_handling: v0
    paths:
    - /leaves
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: notifications
  name: notifications.service
  path: /notifications
  plugins:
  - config:
      credentials: false
      exposed_headers: null
      headers: null
      max_age: null
      methods:
      - GET
      - HEAD
      - PUT
      - PATCH
      - POST
      - DELETE
      - OPTIONS
      - TRACE
      - CONNECT
      origins: null
      preflight_continue: false
      private_network: false
    enabled: true
    name: cors
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - PUT
    - POST
    - DELETE
    name: notifications.route
    path_handling: v0
    paths:
    - /notifications
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: wfhRequests
  name: wfhRequests.service
  path: /wfhRequests
  plugins:
  - config:
      credentials: false
      exposed_headers: null
      headers: null
      max_age: null
      methods:
      - GET
      - HEAD
      - PUT
      - PATCH
      - POST
      - DELETE
      - OPTIONS
      - TRACE
      - CONNECT
      origins: null
      preflight_continue: false
      private_network: false
    enabled: true
    name: cors
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    - PUT
    - POST
    - DELETE
    name: wfhRequests.route
    path_handling: v0
    paths:
    - /wfhRequests
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
