name: Run Unit Tests

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      WFH_REQUEST_URL: ${{ secrets.WFH_REQUEST_URL }}
      EMPLOYEE_URL: ${{ secrets.EMPLOYEE_URL }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      BROKER_CONNECTION_STRING: ${{ secrets.BROKER_CONNECTION_STRING }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/attendance/requirements.txt
          pip install -r backend/employee/requirements.txt
          pip install -r backend/wfhRequests/requirements.txt
          python -m pip install coverage
          
      - name: Run tests
        run: |
          coverage run -m unittest discover -s backend/attendance -p "unit_test.py"
          coverage run -m unittest discover -s backend/employee -p "unit_test.py"
          coverage run -m unittest discover -s backend/wfhRequests -p "unit_test.py"
          
      - name: Report coverage
        run: |
          coverage report
