name: Run Unit Tests

# This workflow runs when code is pushed or a pull request is opened/updated on the main branch
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  run-tests-wfhRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change this to your preferred Python version

      - name: Install dependencies for attendance
        run: |
          cd backend/attendance
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies for employee
        run: |
          cd backend/employee
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies for WFH request
        run: |
          cd backend/wfhRequest
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run attendance tests
        run: python -m unittest attendance/unit_test.py

      - name: Run employee tests
        run: python -m unittest employee/unit_test.py

      - name: Run WFH request tests
        run: python -m unittest wfhRequest/unit_test.py