name: Run Unit Tests

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest, coverage, and xdist
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist coverage

  run-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd backend
          for service in attendance employee wfhRequests; do
            cd $service
            pip install -r requirements.txt
            cd ..
          done

      - name: Run tests in parallel
        run: |
          python -m pip install coverage
          cd backend
          coverage run -m pytest -n auto  # Runs tests in parallel
