name: Run Unit Tests

# This workflow runs when code is pushed or a pull request is opened/updated on the main branch
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change this to your preferred Python version


  run-attendance-tests:
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to complete
    env:
      WFH_REQUEST_URL: ${{ secrets.WFH_REQUEST_URL }}
      EMPLOYEE_URL: ${{ secrets.EMPLOYEE_URL }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      BROKER_CONNECTION_STRING: ${{ secrets.BROKER_CONNECTION_STRING }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install coverage
        run: python -m pip install coverage

      - name: Install dependencies for attendance
        run: |
          cd backend/attendance
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run attendance tests
        run: |
          cd backend/attendance
          coverage run -m unittest unit_test.py

  run-employee-tests:
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to complete
    env:
      WFH_REQUEST_URL: ${{ secrets.WFH_REQUEST_URL }}
      EMPLOYEE_URL: ${{ secrets.EMPLOYEE_URL }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      BROKER_CONNECTION_STRING: ${{ secrets.BROKER_CONNECTION_STRING }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install coverage
        run: python -m pip install coverage

      - name: Install dependencies for employee
        run: |
          cd backend/employee
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run employee tests
        run: |
          cd backend/employee
          coverage run -m unittest unit_test.py

  run-wfh-request-tests:
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to complete
    env:
      WFH_REQUEST_URL: ${{ secrets.WFH_REQUEST_URL }}
      EMPLOYEE_URL: ${{ secrets.EMPLOYEE_URL }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      BROKER_CONNECTION_STRING: ${{ secrets.BROKER_CONNECTION_STRING }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install coverage
        run: python -m pip install coverage
        
      - name: Install dependencies for WFH request
        run: |
          cd backend/wfhRequests
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WFH request tests
        run: |
          cd backend/wfhRequests
          coverage run -m unittest unit_test.py
